#!/bin/bash
# set the name of the app
# this will be used to tag the container
app="bootstrap-docker"

# space separated list of ports to forward
# ports="-p host:container -p host:container"
ports=""

# volumes to include in this container
# volumes="-v `pwd`/data:/data:rw"
volumes=""

# run the container (shell)
eval "docker run -i -t $ports $volumes $app /bin/bash"