#!/usr/bin/env python
from soco import discover
import time
import argparse
import sys

parser = argparse.ArgumentParser(description='Send commands to a sonos zone')
parser.add_argument('command', nargs='+', help='Command to send')
parser.add_argument('-z', '--zone', default='Basement',
                    help='Zone name to send command (Default: Basement)')
parser.add_argument('--commercial-time', type=int, default=5,
                    help='Time in minutes to pause playback for'
                    ' a commercial break (Default 5)')
parser.add_argument('--clear', type=bool, default=False,
                    help='Clear queue before performing command')
args = parser.parse_args()

zones = list(discover())

zone = None

# Uncomment the following to discover zones
for discovered in zones:
    print str(discovered.get_favorite_radio_stations())
    if discovered.player_name == args.zone:
        zone = discovered

if not zone:
    print "No zone found, exiting..."
    sys.exit(1)

print args.command

if args.clear:
    zone.clear_queue()

if args.command[0] == 'play':
    if len(args.command) > 1:
        # Play a URL
        zone.play_uri(args.command[1])
    else:
        # Play whatever is currently set
        zone.play()

if args.command[0] == 'queue':
    if len(args.command) > 1:
        # Queue a URL
        zone.add_uri_to_queue(args.command[1])

if args.command[0] == 'pause':
    zone.pause()

if args.command[0] == 'commercial':
    zone.pause()
    time.sleep(args.commercial_time * 60)
    zone.play()
