#!/usr/bin/env python
from soco import discover
import time
import argparse
import sys

parser = argparse.ArgumentParser(description='Send commands to a sonos zone')
parser.add_argument('command', nargs='+',
                    help="Command to send\n"
                    "(play, pause, commercial, queue, volume, link)")
parser.add_argument('-z', '--zone', default='Office',
                    help='Zone name to send command (Default: Office)')
parser.add_argument('--commercial-time', type=int, default=5,
                    help='Time in minutes to pause playback for'
                    ' a commercial break (Default 5)')
parser.add_argument('--clear', type=bool, default=False,
                    help='Clear queue before performing command')
parser.add_argument('--volume-step', type=int, default=5,
                    help='Percentage to use for volume step')
args = parser.parse_args()

zones = list(discover())

zone = None

# Uncomment the following to discover zones
for discovered in zones:
    # print str(discovered.get_favorite_radio_stations())
    if discovered.player_name == args.zone:
        zone = discovered

if not zone:
    print "No zone found, exiting..."
    sys.exit(1)

if args.clear:
    zone.clear_queue()

if args.command[0] == 'play':
    if len(args.command) > 1:
        # Play a URL
        zone.play_uri(args.command[1])
    else:
        # Play whatever is currently set
        zone.play()

if args.command[0] == 'queue':
    if len(args.command) > 1:
        # Queue a URL
        zone.add_uri_to_queue(args.command[1])

if args.command[0] == 'pause':
    zone.pause()

if args.command[0] == 'commercial':
    zone.pause()
    time.sleep(args.commercial_time * 60)
    zone.play()

if args.command[0] == 'volume':
    if len(args.command) == 1:
        print zone.volume
    else:
        if args.command[1] == 'up':
            zone.volume = zone.volume + args.volume_step
            print "Volume set up {}% to {}%".format(
                str(args.volume_step), str(zone.volume))
        if args.command[1] == 'down':
            zone.volume = zone.volume - args.volume_step
            print "Volume set up {}% to {}%".format(
                str(args.volume_step), str(zone.volume))

if args.command[0] == 'link':
    # Link all zones to this one
    # print "Zones: {}".format(', '.join(zone._visible_zones))
    zone.partymode()
