#!/usr/bin/env python
import datetime
import argparse
import logging
import os
import urllib2
import re
import time
from subprocess import call

today = datetime.date.today()

parser = argparse.ArgumentParser(description='Find a czaban podcast'
                                 ' and play it on sonos. If the podcast'
                                 ' is not found, it will keep trying'
                                 ' until it is found and play it')
parser.add_argument('--hour', type=int, default=1,
                    help='Show hour to play')
parser.add_argument('--date', default=today.strftime("%-m-%-d-%Y"),
                    help='Date to search for, in format %-m-%-d-%Y')
parser.add_argument('--url', default='https://audioboom.com/'
                    'channel/steveczabanyahoosportsradio',
                    help='URL to search for czaban podcasts')
parser.add_argument('--retry-delay', default=5,
                    help='Time in minutes to wait if podcast is not found')
parser.add_argument('--sonos-command', default='play',
                    help='Command to send to sonos when podcast is found')
parser.add_argument('--exit-if-not-found', action='store_true',
                    help='If the podcast is not found on the site,'
                    ' then exit immediately')
parser.add_argument('-d', '--debug', action='store_true',
                    help='Print debug output')
args = parser.parse_args()

# Setup logging options
log_level = logging.DEBUG if args.debug else logging.INFO
log = logging.getLogger(os.path.basename(__file__))
log.setLevel(log_level)
formatter = logging.Formatter('%(asctime)s:%(name)s:%(levelname)s'
                              ':%(funcName)s(%(lineno)i):%(message)s')

# Console Logging
ch = logging.StreamHandler()
ch.setLevel(log_level)
ch.setFormatter(formatter)
log.addHandler(ch)

# File Logging
fh = logging.FileHandler(os.path.basename(__file__) + '.log')
fh.setLevel(log_level)
fh.setFormatter(formatter)
log.addHandler(fh)

log.debug("Args loaded as {}".format(str(args)))

url = None

while not (url or args.exit_if_not_found):
    response = urllib2.urlopen(args.url)
    html = response.read()

    # https://audioboom.com/boos/4078524-1-19-2016-czaban-hour-1
    match = re.search("https://audioboom.com/boos/"
                      ".*-{}-czaban-hour-{}".format(
                          args.date,
                          args.hour),
                      html)
    if match and match.group(0):
        url = match.group(0)
        log.debug("Found URL of {}".format(url))
    else:
        log.warning("Hour {} not found, waiting to retry...".format(
                    args.hour))
        if args.debug:
            for line in html:
                if "czaban-hour" in line:
                    log.debug("Line found: {}".format(line))
        time.sleep(args.retry_delay * 60)

log.info("Found hour {}, playing...".format(args.hour))
call(["sonos", args.sonos_command, "{}.mp3".format(url)])
